[package]
authors = ["Jeff Muizelaar <jmuizelaar@mozilla.com>"]
name = "pdf-extract"
version = "0.6.5-alpha.1"
license = "MIT"
documentation = "https://docs.rs/crate/pdf-extract/"
description = "A library to extract content from pdfs (patched version for hun-law)"
keywords = ["pdf2text", "text", "pdf", "pdf2txt"]
repository = "https://github.com/badicsalex/pdf-extract"
edition = "2021"

[profile.release]
debug = true

[dependencies]
adobe-cmap-parser = "0.3.3"
encoding = "0.2.33"
euclid = "0.20.5"
linked-hash-map = "=0.5.3"
log = "0.4.14"
lopdf = { version = "0.27", default-features = false, features = [ "nom_parser" ] }
phf = { version = "0.10", features = ["macros"] }
postscript = "0.14"
type1-encoding-parser = "0.1.0"
unicode-normalization = "0.1.19"
